#!/usr/bin/env bash
# Verify all 19 target files exist and count baseline lines.
# Generated by the initializer agent — no dev server needed for this refactoring project.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HARNESS_DIR="$ROOT/plugins/harness"

FILES=(
  "$HARNESS_DIR/agents/coordinator.md"
  "$HARNESS_DIR/agents/evaluator.md"
  "$HARNESS_DIR/agents/generator.md"
  "$HARNESS_DIR/agents/initializer.md"
  "$HARNESS_DIR/agents/planner.md"
  "$HARNESS_DIR/agents/releaser.md"
  "$HARNESS_DIR/commands/init.md"
  "$HARNESS_DIR/commands/release.md"
  "$HARNESS_DIR/commands/reset.md"
  "$HARNESS_DIR/commands/run.md"
  "$HARNESS_DIR/commands/session.md"
  "$HARNESS_DIR/skills/harness/SKILL.md"
  "$HARNESS_DIR/skills/harness/references/patterns.md"
  "$HARNESS_DIR/skills/harness/roles/coordinator.md"
  "$HARNESS_DIR/skills/harness/roles/evaluator.md"
  "$HARNESS_DIR/skills/harness/roles/generator.md"
  "$HARNESS_DIR/skills/harness/roles/initializer.md"
  "$HARNESS_DIR/skills/harness/roles/planner.md"
  "$HARNESS_DIR/skills/harness/roles/releaser.md"
)

MISSING=0
TOTAL_LINES=0

for f in "${FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "MISSING: $f"
    MISSING=$((MISSING + 1))
  else
    LINES=$(wc -l < "$f")
    TOTAL_LINES=$((TOTAL_LINES + LINES))
  fi
done

if [ "$MISSING" -gt 0 ]; then
  echo "FAIL — $MISSING target file(s) missing"
  exit 1
fi

echo "OK — all 19 target files exist"
echo "Total baseline lines: $TOTAL_LINES"
