@echo off
REM Baseline smoke test for harness-companion.mjs sprint cycle.
REM Generated by the initializer agent -- edit to match your project.

set "PROJECT_ROOT=%~dp0.."

REM Verify Node.js is available
where node >nul 2>&1
if %ERRORLEVEL% EQU 0 (
  for /f "tokens=*" %%v in ('node --version') do echo OK -- Node.js available ^(%%v^)
) else (
  echo FAIL -- Node.js not found in PATH
  exit /b 1
)

REM Verify target scripts directory location is valid
if exist "%PROJECT_ROOT%\plugins\harness" (
  echo OK -- plugins\harness\ exists ^(scripts\ will be created here^)
) else (
  echo FAIL -- plugins\harness\ directory not found
  exit /b 1
)

REM Verify evaluator role file exists (F-011 target)
if exist "%PROJECT_ROOT%\plugins\harness\skills\harness\roles\evaluator.md" (
  echo OK -- evaluator.md exists ^(F-011 target^)
) else (
  echo FAIL -- evaluator.md not found
  exit /b 1
)

REM Verify harness state files exist
if exist "%PROJECT_ROOT%\.harness\features.json" (
  if exist "%PROJECT_ROOT%\.harness\state.json" (
    echo OK -- harness state files present
  ) else (
    echo FAIL -- harness state files missing
    exit /b 1
  )
) else (
  echo FAIL -- harness state files missing
  exit /b 1
)

echo Baseline verified. Ready for sprint.
