#!/usr/bin/env bash
# Verify the harness baseline for the domain skills project.
# Generated by the initializer agent — edit to match your project.
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "=== Harness Baseline Verification ==="

# Check that required skill template exists
if [ -f "$PROJECT_ROOT/plugins/harness/skills/harness-ea/SKILL.md" ]; then
  echo "OK — harness-ea template skill exists"
else
  echo "FAIL — harness-ea/SKILL.md not found (required as structural template)"
  exit 1
fi

# Check that main SKILL.md exists
if [ -f "$PROJECT_ROOT/plugins/harness/skills/harness/SKILL.md" ]; then
  echo "OK — main harness SKILL.md exists"
else
  echo "FAIL — harness/SKILL.md not found"
  exit 1
fi

# Check that plugin.json is valid JSON
PLUGIN_JSON="$PROJECT_ROOT/plugins/harness/.claude-plugin/plugin.json"
if node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$PLUGIN_JSON" 2>/dev/null; then
  echo "OK — plugin.json is valid JSON"
else
  echo "FAIL — plugin.json is not valid JSON"
  exit 1
fi

# Check harness artifacts
for artifact in features.json progress.md state.json config.json spec.md; do
  if [ -f "$PROJECT_ROOT/.harness/$artifact" ]; then
    echo "OK — .harness/$artifact exists"
  else
    echo "FAIL — .harness/$artifact missing"
    exit 1
  fi
done

echo ""
echo "=== Baseline verification complete ==="
echo "Next: begin Sprint 1 targeting F-001 (harness-ba domain skill)"
