#!/usr/bin/env bash
# Verify baseline files exist for the README Sync feature.
# Generated by the initializer agent — edit to match your project.
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Smoke test — verify the releaser role file exists
if [ -f "$PROJECT_ROOT/plugins/harness/skills/harness/roles/releaser.md" ]; then
  echo "OK — releaser role file exists"
else
  echo "FAIL — releaser role file not found at plugins/harness/skills/harness/roles/releaser.md"
  exit 1
fi

# Verify the releaser agent stub exists
if [ -f "$PROJECT_ROOT/plugins/harness/agents/releaser.md" ]; then
  echo "OK — releaser agent stub exists"
else
  echo "FAIL — releaser agent stub not found at plugins/harness/agents/releaser.md"
  exit 1
fi

echo "Baseline verified. Ready for sprint."
