@echo off
REM Verify the harness baseline for the domain skills project.
REM Generated by the initializer agent — edit to match your project.

echo === Harness Baseline Verification ===

REM Check that required skill template exists
if exist "%~dp0..\plugins\harness\skills\harness-ea\SKILL.md" (
  echo OK — harness-ea template skill exists
) else (
  echo FAIL — harness-ea/SKILL.md not found (required as structural template)
  exit /b 1
)

REM Check that main SKILL.md exists
if exist "%~dp0..\plugins\harness\skills\harness\SKILL.md" (
  echo OK — main harness SKILL.md exists
) else (
  echo FAIL — harness/SKILL.md not found
  exit /b 1
)

REM Check that plugin.json is valid JSON
node -e "JSON.parse(require('fs').readFileSync('%~dp0..\\plugins\\harness\\.claude-plugin\\plugin.json','utf8'))" 2>nul
if %ERRORLEVEL% EQU 0 (
  echo OK — plugin.json is valid JSON
) else (
  echo FAIL — plugin.json is not valid JSON
  exit /b 1
)

REM Check harness artifacts
for %%F in (features.json progress.md state.json config.json spec.md) do (
  if exist "%~dp0%%F" (
    echo OK — .harness/%%F exists
  ) else (
    echo FAIL — .harness/%%F missing
    exit /b 1
  )
)

echo.
echo === Baseline verification complete ===
echo Next: begin Sprint 1 targeting F-001 (harness-ba domain skill)
