@echo off
REM Baseline smoke test for harness v2.2.3 cycle.
REM Generated by the initializer agent -- edit to match your project.

set "PROJECT_ROOT=%~dp0.."
set "SCRIPTS_DIR=%PROJECT_ROOT%\plugins\harness\scripts"
set "HOOKS_DIR=%PROJECT_ROOT%\plugins\harness\hooks"

echo === Harness v2.2.3 Baseline Smoke Test ===

REM 1. Verify Node.js is available
where node >nul 2>&1
if %ERRORLEVEL% EQU 0 (
  for /f "tokens=*" %%v in ('node --version') do echo OK -- Node.js available ^(%%v^)
) else (
  echo FAIL -- Node.js not found in PATH
  exit /b 1
)

REM 2. Verify scripts directory exists
if exist "%SCRIPTS_DIR%" (
  echo OK -- scripts directory exists
) else (
  echo FAIL -- scripts directory not found
  exit /b 1
)

REM 3. Verify harness-companion.mjs entry point exists
if exist "%SCRIPTS_DIR%\harness-companion.mjs" (
  echo OK -- harness-companion.mjs exists
) else (
  echo FAIL -- harness-companion.mjs not found
  exit /b 1
)

REM 4. Verify lib modules exist
for %%m in (state.mjs features.mjs git.mjs artifacts.mjs progress.mjs metrics.mjs events.mjs) do (
  if exist "%SCRIPTS_DIR%\lib\%%m" (
    echo OK -- lib\%%m exists
  ) else (
    echo FAIL -- lib\%%m not found
    exit /b 1
  )
)

REM 5. Verify harness state files exist
if exist "%PROJECT_ROOT%\.harness\features.json" (
  if exist "%PROJECT_ROOT%\.harness\state.json" (
    echo OK -- harness state files present
  ) else (
    echo FAIL -- harness state files missing
    exit /b 1
  )
) else (
  echo FAIL -- harness state files missing
  exit /b 1
)

REM 6. Verify hooks.json exists
if exist "%HOOKS_DIR%\hooks.json" (
  echo OK -- hooks.json exists
) else (
  echo FAIL -- hooks.json not found
  exit /b 1
)

REM 7. Verify harness-companion.mjs responds to help
node "%SCRIPTS_DIR%\harness-companion.mjs" help >nul 2>&1
if %ERRORLEVEL% EQU 0 (
  echo OK -- harness-companion.mjs help responds
) else (
  echo FAIL -- harness-companion.mjs help did not respond
  exit /b 1
)

echo.
echo Baseline verified. Ready for sprint.
