#!/usr/bin/env bash
# Build verification script for the harness plugin.
# This plugin has no compiled code -- verification is structural.
# Generated by the initializer agent.
set -e

PLUGIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0
FAIL=0
ERRORS=""

check_file() {
  local filepath="$1"
  if [ -f "$PLUGIN_DIR/$filepath" ]; then
    PASS=$((PASS + 1))
  else
    FAIL=$((FAIL + 1))
    ERRORS="$ERRORS\n  MISSING: $filepath"
  fi
}

check_json() {
  local filepath="$1"
  if [ -f "$PLUGIN_DIR/$filepath" ]; then
    if node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$PLUGIN_DIR/$filepath" 2>/dev/null || \
       python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$PLUGIN_DIR/$filepath" 2>/dev/null || \
       python -c "import json,sys; json.load(open(sys.argv[1]))" "$PLUGIN_DIR/$filepath" 2>/dev/null; then
      PASS=$((PASS + 1))
    else
      FAIL=$((FAIL + 1))
      ERRORS="$ERRORS\n  INVALID JSON: $filepath"
    fi
  else
    FAIL=$((FAIL + 1))
    ERRORS="$ERRORS\n  MISSING (json check): $filepath"
  fi
}

check_no_stale_refs() {
  local filepath="$1"
  local pattern="$2"
  local label="$3"
  if [ -f "$PLUGIN_DIR/$filepath" ]; then
    if grep -q "$pattern" "$PLUGIN_DIR/$filepath" 2>/dev/null; then
      FAIL=$((FAIL + 1))
      ERRORS="$ERRORS\n  STALE REF in $filepath: found '$pattern' ($label)"
    else
      PASS=$((PASS + 1))
    fi
  fi
}

echo "=== Harness Plugin Verification ==="
echo "Plugin directory: $PLUGIN_DIR"
echo ""

# --- Section 1: Core files that should exist right now ---
echo "-- Checking core existing files --"
check_file ".codex-plugin/plugin.json"
check_file "install.sh"
check_file "install.bat"
check_file "README.md"
check_file "skills/harness/SKILL.md"
check_file "skills/harness/references/patterns.md"

# --- Section 2: Existing agent files ---
echo "-- Checking existing agent files --"
check_file "agents/initializer.md"
check_file "agents/planner.md"
check_file "agents/generator.md"
check_file "agents/evaluator.md"
check_file "agents/coordinator.md"
check_file "agents/releaser.md"
check_file "agents/tester.md"
check_file "agents/reviewer.md"
check_file "agents/architect.md"

# --- Section 3: Existing role files ---
echo "-- Checking existing role files --"
check_file "skills/harness/roles/initializer.md"
check_file "skills/harness/roles/planner.md"
check_file "skills/harness/roles/generator.md"
check_file "skills/harness/roles/evaluator.md"
check_file "skills/harness/roles/coordinator.md"
check_file "skills/harness/roles/releaser.md"
check_file "skills/harness/roles/tester.md"
check_file "skills/harness/roles/reviewer.md"
check_file "skills/harness/roles/architect.md"

# --- Section 4: Command files ---
echo "-- Checking command files --"
check_file "commands/harness:init.md"
check_file "commands/harness:run.md"
check_file "commands/harness:session.md"
check_file "commands/harness:reset.md"
check_file "commands/harness:release.md"

# --- Section 5: JSON validation ---
echo "-- Validating JSON files --"
check_json ".codex-plugin/plugin.json"
check_json "artifacts/feature-list.json"
check_json "artifacts/run-state.json"

# --- Section 6: Install script syntax ---
echo "-- Checking install.sh syntax --"
if bash -n "$PLUGIN_DIR/install.sh" 2>/dev/null; then
  PASS=$((PASS + 1))
  echo "  install.sh: syntax OK"
else
  FAIL=$((FAIL + 1))
  ERRORS="$ERRORS\n  SYNTAX ERROR: install.sh"
fi

# --- Section 7: Stale reference checks (enabled after F-001) ---
echo "-- Checking for stale references --"
for f in agents/*.md skills/harness/SKILL.md skills/harness/roles/*.md skills/harness/references/*.md; do
  check_no_stale_refs "$f" "skills/long-running-harness" "old skill path"
  check_no_stale_refs "$f" "feature-list\.json" "old feature list filename"
  check_no_stale_refs "$f" "run-state\.json" "old run state filename"
done

# Check command files (with colon in name)
for f in "commands/harness:init.md" "commands/harness:run.md" "commands/harness:session.md" "commands/harness:reset.md" "commands/harness:release.md"; do
  check_no_stale_refs "$f" "skills/long-running-harness" "old skill path"
  check_no_stale_refs "$f" "feature-list\.json" "old feature list filename"
  check_no_stale_refs "$f" "run-state\.json" "old run state filename"
  check_no_stale_refs "$f" "long-running-harness" "old plugin name"
done

echo ""
echo "=== Results ==="
echo "PASS: $PASS"
echo "FAIL: $FAIL"
if [ $FAIL -gt 0 ]; then
  echo -e "\nFailures:$ERRORS"
  echo ""
  echo "RESULT: FAIL"
  exit 1
else
  echo ""
  echo "RESULT: PASS"
  exit 0
fi
